# Executive Summary

The [**Reliability Modeling Toolkit (RMT)**](https://github.com/Center-for-Risk-and-Reliability/RMT) is a free-of-charge open-source R-based library of educational tools developed at the University of Maryland’s (UMD) Center for Risk and Reliability.  Launched in 2022 (as v. 1.0.0), the RMT is designed to execute computationally involved and challenging reliability modeling and analytical calculations based on probabilistic physics of failure (PPoF) and accelerated testing (AT) procedures, including accelerated life testing (ALT) and accelerated degradation testing (ADT).  For graduate students, educators, and industry including aerospace, manufacturing, and defense, the RMT provides a cost-free alternative to existing reliability analysis software (e.g. Reliasoft or Minitab).

However, its reach is limited by its exclusivity to GitHub as a download port.  Without a download port on CRAN, the RMT would be accessible only by general “word-of-mouth” and mostly unavailable to the global R userbase.  Furthermore, although the RMT has a well-documented help folder, it currently lacks online ready examples of operation using engineering related case-studies and examples.

The goal of the proposed project is to apply crucial modernization procedures to the RMT’s framework and infrastructure and thus transform it into a robust, CRAN ready package for distribution in six-months from the project start.  Within this six-month period: (1) older code structures and functions will be restructured and updated, (2) an expanded test case folder for `testthat` will be developed for the RMT tools, (3) an interactive pkgdown tutorial and documentation site will be developed and uploaded, and (4) the RMT v. 2.0.0 will be submitted to CRAN.

The requested $10,000 will be directly used for labor costs for the developer and maintainer of the RMT for the purpose of executing the project tasks, testing and validating the tools, and delivering a fully updated reliability toolkit to the broader R community.
