# Signatories

## Project team

**Principal Investigator & Lead Developer – Dr. Reuel Smith, University of Maryland and Montgomery College**

Sole project lead, package maintainer, and lead developer of the [Reliability Modeling Toolkit (RMT)](https://github.com/Center-for-Risk-and-Reliability/RMT) and is well versed with concepts of R coding, testing, and debugging and reliability engineering including accelerated testing, probabilistic physics of failure, and modeling.  Executes all code refactoring, `testthat` suite development and integration, and CRAN submission tasks.


## Contributors

**Co-Developer & Project Advisor – Prof. Mohammad Modarres, University of Maryland**
Senior professor with the Center for Risk and Reliability and the original co-designer and advisor for the RMT.  Provides valuable feedback and review, datasets for testing, and validation for the RMT’s tool algorithms and functions.


## Consulted

**Reliability Engineering & R User Community**

Faculty within the Center for Risk and Reliability as well as attendees at the Reliability and Maintainability Symposium (RAMS) have been regularly consulted for feedback concerning the direction of the RMT.

