---
bibliography: references.bib
---

# The Problem

The *Reliability Modeling Toolkit (RMT)* is a free-of-charge open-source R-based library of educational tools specifically designed to execute computationally involved and challenging reliability modeling and analytical calculations based on *probabilistic physics of failure (PPoF)*, *probability estimation*, and *accelerated testing (AT) procedures*, including *accelerated life testing (ALT)* and *accelerated degradation testing (ADT)*.  This creates a free-of-charge alternative to high-cost reliability software packages for students, educators, and the engineering industry.  

While R excels at general statistical modeling, these reliability toolsets are somewhat fragmented between different single-purpose libraries. The RMT by contrast seeks to unify toolsets such that they are readily available to the user for a variety of reliability-based operations, and R is in need of a dedicated package that brings several reliability analysis toolsets together.

Its exclusive availability on GitHub however creates a barrier to users seeking a “pick-up-and-use” library such as those available on CRAN.  Its current repository only makes it visible to those who know of it or by “word-of-mouth,” whereas CRAN is open to the global R community as a whole.  Since its initial release in 2022 (as v. 1.0.0), the RMT’s userbase has grown slowly and feedback has helped in its development into a more robust and versatile reliability software package.  By solving this issue of CRAN availability for the RMT, reliability engineers within the R community will have direct access for download and installation through the CRAN network and reduce their reliance on costly software alternatives.
