# The proposal

## Overview
This project seeks to fully prepare the RMT for entry into CRAN and the greater R community which will involve a complete refactoring, validation, and documentation of its existing ~150 tools.  By modernizing its existing code structure and implementing a fully test-driven development plan, the RMT will fully integrate into the R community as a standard for open-source reliability analysis.

The proposed project timeline will go as follows:

- **Month 1-2**: Script restructuring, dependency cleanup, and resolution of any warnings or errors
- **Month 3-4**: Test-driven development phase where test cases will be developed for the RMT’s `testthat` folder
- **Month 5**: Develop structured documentation vignettes for use of the RMT’s toolsets (probability plotting, ALT, and ADT)
- **Month 6**: Submission of the RMT 2.0.0 package to CRAN and R community outreach


## Detail

### Minimum Viable Product

The minimum outcome from this project will be a refit package of the RMT uploaded onto CRAN with a complete `R CMD check` pass and no detected errors or warnings.  The following tools and tool functions should also be operating: 

-	Probability plotting and distribution fitting tools utilizing least squares and maximum likelihood estimation (MLE)
-	MLE and Bayesian model paramerter estimation routines for ALT and ADT models
-	More than 85% tests covered and modified and verified by `covr`
-	A live website or `pkgdown` pages containing RMT tutorials with reproducible examples


### Architecture

The RMT uses the standard R package conventions built around both S3/S4 object systems for standard model input/output flow.  Plots generated by the RMT use `ggplot2` for publication ready images.  The Bayesian operations are conducted by `rstan` which makes use of powerful Markov Chain Monte Carlo (MCMC) analysis.  Package checking and test checking is conducted by `testthat` integrated with GitHub Actions workflows across Windows, macOS, and Linux runners.

### Assumptions

The project operates under the assumption that the core mathematics and logic used in the RMT code can be verified by existing reliability analysis software and functions.  The scripts themselves however require software refactoring, namespace optimization, and package packaging rather than exploratory algorithmic development.

### External dependencies

The RMT’s dependencies are as follows: `ggplot2`, `rstan`, `pracma`, `testthat`, `roxygen2`, `pkgdown`, `knitr`, and`rmarkdown`.
