# Project plan

## Start-up phase

- **Platform Setup**: (*DONE*) Established GitHub repository for the RMT under the [UMD Center for Risk and Reliability organization account](https://github.com/Center-for-Risk-and-Reliability/RMT)
-	**Licensing**: (*DONE*) GNU General Public License v3.0 (GPL-3) has been established for users to ensure open-source access and protect subsequent distribution.
-	**Reporting Framework**: Establish GitHub issue tracking to monitor progress on a bi-weekly basis


## Technical delivery

**Stage 1: RMT Tool Architecture (est. target window Month 1-2)** - Restructure scripts and functions, standardize argument syntax and eliminate any `R CMD check` warnings or errors

**Stage 2: Validation of RMT Tools (est. target window Month 3-4)** - Develop test cases for the RMT’s `testthat` folder that checks for logic issues for benchmark datasets

**Stage 3: Documentation Update and Creation (est. target window Month 5)** - Complete `roxygen2` documentation tags write RMT’s toolset vignettes and upload `pkgdown` site

**Stage 4: Release (est. target window Month 6)** - Submit RMT 2.0.0 package to CRAN and update on GitHub


## Other aspects

-	**Open-Source Licensing**: GNU General Public License v3.0 (GPL-3)
-	**Community Outreach and Engagement**: 
--	Post launch of project and share project updates on various blogs and websites including the R Consortium Blog, CRR website, and LinkedIn platform
--	Publish a technical delivery post upon CRAN acceptance featuring reproducible ALT examples.
-- Share updates with reliability engineering community groups and present results at upcoming industry forums (e.g., RAMS).


## Budget & funding plan

The total requested amount is $10,000 which is expected to be used entirely for labor.  Funds will not be used for travel, publication fees, food or lodging, hardware, or any indirect costs per ISC guidelines.  Approximately $5,000 will cover labor for the first three months (up to the middle of Stage 2) and the remaining $5,000 will be dispensed upon the conclusion of the six-month project when the RMT 2.0.0 package is submitted to CRAN and updated on GitHub.
